### ISSUE TITLE
tab height fix

### ISSUE THREAD

**Issue by ra81** [SandyTheGreat/-1.1-RPG-Style-Inventory-V3.3.1-#5]
great mod. 
when i open the tab i can't see other inventory items without scrolling. even if pawn has only 1 or two items. It would be better to see all at once. I can fix cod by self and i set height to 700. this suit all situations.  if you wish you can fix this in your code.

thank you!

**Comment by SandyTheGreat** [comment]
Thanks. Sorry for the very very late reply.
I only have a 14" laptop. Using more height than I did, will make the tab go out of my screen. I would like to add a setting for that, but I am too much of an amateur in C# and game modding. Its good that you are able to adjust to your liking.

**Comment by SandyTheGreat** [comment]
Hi. I added options to change the size of the gear tab in the mod settings. So i'll close this issue. I hope u dont mind. Will update the mod in a couple days.

**Comment by ra81** [comment]
nice!
I'm going to try new version soon.
